product_lines:
   - name: 产品线B
    watch_directories:D:\图包
      - path:D:\图包
        extract_mode: nested
    notification:
      dingtalk:
        webhook_url: https://oapi.dingtalk.com/robot/send?access_token=ANOTHER_ACCESS_TOKEN